services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      args:
        HOST: ${NGINX_HOST}
        PORT: ${NGINX_PORT_INTERNAL}
        SERVER_NAME: ${NGINX_NAME}
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - backend

  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      dockerfile: Dockerfile
      args:
        POETRY_VERSION: ${POETRY_VERSION}
        APP_ENV: ${APP_ENV}
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'
    ports:
      - 8080:8888
    depends_on:
      - "postgres"

volumes:
  db-data:
